version: '3.9'

services:
  ftp-server:
    image: delfer/alpine-ftp-server
    environment:
      - USERS=user|blabla#123|/home/user
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    volumes:
      - storage:/home/user
    network_mode: "host"
  codegen:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - codegen.env          
    volumes:
      - storage:/server      
    depends_on:
      - api
  api:
    build:
      context: ../
      dockerfile: src/WebApi/Dockerfile
    ports:
      - 8081:8081
    env_file:                     
      - codegen.env
volumes:
  storage:
    