version: '3.9'

services:  
  proxy:
    image: "ghcr.io/aschuhde/perspektivenfabrik-proxy:main"
    ports:
      - "9000:9000"
      - "9443:9443"        
    env_file:
      - global-access-token.env
      - cert.env
      - ports.env
      - proxy.env   
    pull_policy: always
  nginx:
    image: "ghcr.io/aschuhde/perspektivenfabrik-frontend-container:main"
    env_file:
      - ports.env
    pull_policy: always
  angular:
    image: "ghcr.io/aschuhde/perspektivenfabrik-frontend:main"
    env_file:
      - ports.env
    pull_policy: always
  api:
    image: "ghcr.io/aschuhde/perspektivenfabrik-api:main"
    env_file:
      - db-connection.env      
      - ports.env
      - api.env
      - jwt.env
    environment:
      - CONFIG_Serilog__MinimumLevel__Default=Debug      
    pull_policy: always
  postgres:    
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ports.env
      - db-connection.env
    ports:
      - "5432:5432"
    pull_policy: always
volumes:
  postgres_db:
    driver: local
