/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationModelsApiModelsApiMaterialSpecification } from './applicationModelsApiModelsApiMaterialSpecification';
import { ApplicationModelsApiModelsApiQuantitySpecification } from './applicationModelsApiModelsApiQuantitySpecification';
import { ApplicationModelsApiModelsApiRequirementSpecification } from './applicationModelsApiModelsApiRequirementSpecification';
import { ApplicationModelsApiModelsApiTimeSpecification } from './applicationModelsApiModelsApiTimeSpecification';

export interface ApplicationModelsApiModelsApiRequirementSpecificationMoney extends ApplicationModelsApiModelsApiRequirementSpecification { 
    materialSpecifications?: Array<ApplicationModelsApiModelsApiMaterialSpecification>;
}