/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ApplicationModelsApiModelsApiContactSpecificationTypes = 'Base' | 'PhoneNumber' | 'MailAddress' | 'PostalAddress';

export const ApplicationModelsApiModelsApiContactSpecificationTypes = {
    Base: 'Base' as ApplicationModelsApiModelsApiContactSpecificationTypes,
    PhoneNumber: 'PhoneNumber' as ApplicationModelsApiModelsApiContactSpecificationTypes,
    MailAddress: 'MailAddress' as ApplicationModelsApiModelsApiContactSpecificationTypes,
    PostalAddress: 'PostalAddress' as ApplicationModelsApiModelsApiContactSpecificationTypes
};