/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationModelsApiModelsApiLocationSpecification } from './applicationModelsApiModelsApiLocationSpecification';
import { ApplicationModelsApiModelsApiQuantitySpecification } from './applicationModelsApiModelsApiQuantitySpecification';
import { ApplicationModelsApiModelsApiRequirementSpecification } from './applicationModelsApiModelsApiRequirementSpecification';
import { ApplicationModelsApiModelsApiSkillSpecification } from './applicationModelsApiModelsApiSkillSpecification';
import { ApplicationModelsApiModelsApiTimeSpecification } from './applicationModelsApiModelsApiTimeSpecification';
import { ApplicationModelsApiModelsApiWorkAmountSpecification } from './applicationModelsApiModelsApiWorkAmountSpecification';

export interface ApplicationModelsApiModelsApiRequirementSpecificationPerson extends ApplicationModelsApiModelsApiRequirementSpecification { 
    skillSpecifications?: Array<ApplicationModelsApiModelsApiSkillSpecification>;
    locationSpecifications?: Array<ApplicationModelsApiModelsApiLocationSpecification>;
    workAmountSpecifications?: Array<ApplicationModelsApiModelsApiWorkAmountSpecification>;
}