/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationModelsApiModelsApiBaseEntity } from './applicationModelsApiModelsApiBaseEntity';
import { ApplicationModelsApiModelsApiContactSpecification } from './applicationModelsApiModelsApiContactSpecification';
import { ApplicationModelsApiModelsApiDescriptionSpecification } from './applicationModelsApiModelsApiDescriptionSpecification';
import { ApplicationModelsApiModelsApiGraphicsSpecification } from './applicationModelsApiModelsApiGraphicsSpecification';
import { ApplicationModelsApiModelsApiLocationSpecification } from './applicationModelsApiModelsApiLocationSpecification';
import { ApplicationModelsApiModelsApiModificationHistory } from './applicationModelsApiModelsApiModificationHistory';
import { ApplicationModelsApiModelsApiOrganization } from './applicationModelsApiModelsApiOrganization';
import { ApplicationModelsApiModelsApiPerson } from './applicationModelsApiModelsApiPerson';
import { ApplicationModelsApiModelsApiProjectConnection } from './applicationModelsApiModelsApiProjectConnection';
import { ApplicationModelsApiModelsApiProjectTag } from './applicationModelsApiModelsApiProjectTag';
import { ApplicationModelsApiModelsApiRequirementSpecification } from './applicationModelsApiModelsApiRequirementSpecification';
import { ApplicationModelsApiModelsApiTimeSpecification } from './applicationModelsApiModelsApiTimeSpecification';
import { DomainDataTypesFormattedTitle } from './domainDataTypesFormattedTitle';
import { DomainDataTypesTranslationValue } from './domainDataTypesTranslationValue';
import { DomainEnumsApprovalStatus } from './domainEnumsApprovalStatus';
import { DomainEnumsProjectPhase } from './domainEnumsProjectPhase';
import { DomainEnumsProjectType } from './domainEnumsProjectType';
import { DomainEnumsProjectVisibility } from './domainEnumsProjectVisibility';

export interface ApplicationModelsApiModelsApiProject extends ApplicationModelsApiModelsApiBaseEntity { 
    phase?: DomainEnumsProjectPhase;
    type?: DomainEnumsProjectType;
    visibility?: DomainEnumsProjectVisibility;
    approvalStatus?: DomainEnumsApprovalStatus;
    locationSpecifications?: Array<ApplicationModelsApiModelsApiLocationSpecification>;
    timeSpecifications?: Array<ApplicationModelsApiModelsApiTimeSpecification>;
    requirementSpecifications?: Array<ApplicationModelsApiModelsApiRequirementSpecification>;
    contactSpecifications?: Array<ApplicationModelsApiModelsApiContactSpecification>;
    projectName?: string;
    projectNameTranslations?: Array<DomainDataTypesTranslationValue>;
    projectTags?: Array<ApplicationModelsApiModelsApiProjectTag>;
    projectTitle?: DomainDataTypesFormattedTitle;
    descriptionSpecifications?: Array<ApplicationModelsApiModelsApiDescriptionSpecification>;
    graphicsSpecifications?: Array<ApplicationModelsApiModelsApiGraphicsSpecification>;
    connectedOrganizationsSameAsOwner?: boolean;
    connectedOrganizations?: Array<ApplicationModelsApiModelsApiOrganization>;
    owner?: ApplicationModelsApiModelsApiPerson;
    contributors?: Array<ApplicationModelsApiModelsApiPerson>;
    relatedProjects?: Array<ApplicationModelsApiModelsApiProjectConnection>;
}