/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ApplicationPostConfirmOtpPostConfirmOtpOtpStatus = 'Confirmed' | 'Expired' | 'Wrong' | 'NotRequired';

export const ApplicationPostConfirmOtpPostConfirmOtpOtpStatus = {
    Confirmed: 'Confirmed' as ApplicationPostConfirmOtpPostConfirmOtpOtpStatus,
    Expired: 'Expired' as ApplicationPostConfirmOtpPostConfirmOtpOtpStatus,
    Wrong: 'Wrong' as ApplicationPostConfirmOtpPostConfirmOtpOtpStatus,
    NotRequired: 'NotRequired' as ApplicationPostConfirmOtpPostConfirmOtpOtpStatus
};