/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ApplicationModelsApiModelsApiLocationSpecificationTypes = 'Base' | 'Remote' | 'Region' | 'Coordinates' | 'Address' | 'Name' | 'EntireProvince';

export const ApplicationModelsApiModelsApiLocationSpecificationTypes = {
    Base: 'Base' as ApplicationModelsApiModelsApiLocationSpecificationTypes,
    Remote: 'Remote' as ApplicationModelsApiModelsApiLocationSpecificationTypes,
    Region: 'Region' as ApplicationModelsApiModelsApiLocationSpecificationTypes,
    Coordinates: 'Coordinates' as ApplicationModelsApiModelsApiLocationSpecificationTypes,
    Address: 'Address' as ApplicationModelsApiModelsApiLocationSpecificationTypes,
    Name: 'Name' as ApplicationModelsApiModelsApiLocationSpecificationTypes,
    EntireProvince: 'EntireProvince' as ApplicationModelsApiModelsApiLocationSpecificationTypes
};