/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationCommonResponseJsonResponse } from './applicationCommonResponseJsonResponse';
import { ApplicationModelsApiModelsApiMaterial } from './applicationModelsApiModelsApiMaterial';
import { ApplicationModelsApiModelsApiSkill } from './applicationModelsApiModelsApiSkill';
import { ApplicationModelsApiModelsApiTag } from './applicationModelsApiModelsApiTag';

export interface ApplicationGetAutocompleteEntriesGetAutocompleteEntriesGetAutocompleteEntriesResponse extends ApplicationCommonResponseJsonResponse { 
    tags?: Array<ApplicationModelsApiModelsApiTag>;
    skills?: Array<ApplicationModelsApiModelsApiSkill>;
    materials?: Array<ApplicationModelsApiModelsApiMaterial>;
}