/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationApiDataTypesApiTranslationValue } from './applicationApiDataTypesApiTranslationValue';
import { ApplicationModelsApiModelsApiBaseEntity } from './applicationModelsApiModelsApiBaseEntity';
import { ApplicationModelsApiModelsApiContactSpecification } from './applicationModelsApiModelsApiContactSpecification';
import { ApplicationModelsApiModelsApiDescriptionSpecification } from './applicationModelsApiModelsApiDescriptionSpecification';
import { ApplicationModelsApiModelsApiGraphicsSpecification } from './applicationModelsApiModelsApiGraphicsSpecification';
import { ApplicationModelsApiModelsApiLocationSpecification } from './applicationModelsApiModelsApiLocationSpecification';
import { ApplicationModelsApiModelsApiModificationHistory } from './applicationModelsApiModelsApiModificationHistory';
import { ApplicationModelsApiModelsApiOrganizationReference } from './applicationModelsApiModelsApiOrganizationReference';
import { ApplicationModelsApiModelsApiPerson } from './applicationModelsApiModelsApiPerson';
import { ApplicationModelsApiModelsApiPersonReference } from './applicationModelsApiModelsApiPersonReference';
import { ApplicationModelsApiModelsApiProjectReference } from './applicationModelsApiModelsApiProjectReference';
import { ApplicationModelsApiModelsApiProjectTag } from './applicationModelsApiModelsApiProjectTag';
import { ApplicationModelsApiModelsApiRequirementSpecification } from './applicationModelsApiModelsApiRequirementSpecification';
import { ApplicationModelsApiModelsApiTimeSpecification } from './applicationModelsApiModelsApiTimeSpecification';
import { DomainDataTypesFormattedTitle } from './domainDataTypesFormattedTitle';
import { DomainEnumsProjectPhase } from './domainEnumsProjectPhase';
import { DomainEnumsProjectType } from './domainEnumsProjectType';
import { DomainEnumsProjectVisibility } from './domainEnumsProjectVisibility';

export interface ApplicationModelsApiModelsApiProjectBody extends ApplicationModelsApiModelsApiBaseEntity { 
    phase?: DomainEnumsProjectPhase;
    type?: DomainEnumsProjectType;
    visibility?: DomainEnumsProjectVisibility;
    locationSpecifications?: Array<ApplicationModelsApiModelsApiLocationSpecification>;
    timeSpecifications?: Array<ApplicationModelsApiModelsApiTimeSpecification>;
    requirementSpecifications?: Array<ApplicationModelsApiModelsApiRequirementSpecification>;
    contactSpecifications?: Array<ApplicationModelsApiModelsApiContactSpecification>;
    projectName?: string;
    projectNameTranslations?: Array<ApplicationApiDataTypesApiTranslationValue>;
    projectTags?: Array<ApplicationModelsApiModelsApiProjectTag>;
    projectTitle?: DomainDataTypesFormattedTitle;
    descriptionSpecifications?: Array<ApplicationModelsApiModelsApiDescriptionSpecification>;
    graphicsSpecifications?: Array<ApplicationModelsApiModelsApiGraphicsSpecification>;
    connectedOrganizationsSameAsOwner?: boolean;
    connectedOrganizations?: Array<ApplicationModelsApiModelsApiOrganizationReference>;
    owner?: ApplicationModelsApiModelsApiPersonReference;
    contributors?: Array<ApplicationModelsApiModelsApiPersonReference>;
    relatedProjects?: Array<ApplicationModelsApiModelsApiProjectReference>;
}