/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationCommonResponseJsonResponse } from './applicationCommonResponseJsonResponse';
import { ApplicationModelsApiModelsApiContactSpecificationTypes } from './applicationModelsApiModelsApiContactSpecificationTypes';
import { ApplicationModelsApiModelsApiLocationSpecificationTypes } from './applicationModelsApiModelsApiLocationSpecificationTypes';
import { ApplicationModelsApiModelsApiRequirementSpecificationTypes } from './applicationModelsApiModelsApiRequirementSpecificationTypes';
import { ApplicationModelsApiModelsApiTimeSpecificationTypes } from './applicationModelsApiModelsApiTimeSpecificationTypes';

export interface ApplicationGetJsonTypeDiscriminatorNamesGetJsonTypeDiscriminatorNamesGetJsonTypeDiscriminatorNamesResponse extends ApplicationCommonResponseJsonResponse { 
    apiTimeSpecificationTypes?: Array<ApplicationModelsApiModelsApiTimeSpecificationTypes>;
    apiLocationSpecificationTypes?: Array<ApplicationModelsApiModelsApiLocationSpecificationTypes>;
    apiRequirementSpecificationTypes?: Array<ApplicationModelsApiModelsApiRequirementSpecificationTypes>;
    apiContactSpecificationTypes?: Array<ApplicationModelsApiModelsApiContactSpecificationTypes>;
}