/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsApprovalStatus = 'Pending' | 'AutoApproved' | 'Approved' | 'Rejected' | 'Unknown';

export const DomainEnumsApprovalStatus = {
    Pending: 'Pending' as DomainEnumsApprovalStatus,
    AutoApproved: 'AutoApproved' as DomainEnumsApprovalStatus,
    Approved: 'Approved' as DomainEnumsApprovalStatus,
    Rejected: 'Rejected' as DomainEnumsApprovalStatus,
    Unknown: 'Unknown' as DomainEnumsApprovalStatus
};