/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsProjectPhase = 'Idea' | 'Request' | 'Planning' | 'Ongoing' | 'Finished' | 'Cancelled' | 'Unkown';

export const DomainEnumsProjectPhase = {
    Idea: 'Idea' as DomainEnumsProjectPhase,
    Request: 'Request' as DomainEnumsProjectPhase,
    Planning: 'Planning' as DomainEnumsProjectPhase,
    Ongoing: 'Ongoing' as DomainEnumsProjectPhase,
    Finished: 'Finished' as DomainEnumsProjectPhase,
    Cancelled: 'Cancelled' as DomainEnumsProjectPhase,
    Unkown: 'Unkown' as DomainEnumsProjectPhase
};