/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsHistoryEntryType = 'Created' | 'Deleted' | 'Updated' | 'Special' | 'Unknown' | 'Approved';

export const DomainEnumsHistoryEntryType = {
    Created: 'Created' as DomainEnumsHistoryEntryType,
    Deleted: 'Deleted' as DomainEnumsHistoryEntryType,
    Updated: 'Updated' as DomainEnumsHistoryEntryType,
    Special: 'Special' as DomainEnumsHistoryEntryType,
    Unknown: 'Unknown' as DomainEnumsHistoryEntryType,
    Approved: 'Approved' as DomainEnumsHistoryEntryType
};