/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsProjectType = 'Idea' | 'Inspiration' | 'Project' | 'ProjectRequest' | 'Unkown';

export const DomainEnumsProjectType = {
    Idea: 'Idea' as DomainEnumsProjectType,
    Inspiration: 'Inspiration' as DomainEnumsProjectType,
    Project: 'Project' as DomainEnumsProjectType,
    ProjectRequest: 'ProjectRequest' as DomainEnumsProjectType,
    Unkown: 'Unkown' as DomainEnumsProjectType
};