/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsProjectVisibility = 'Draft' | 'Internal' | 'Public' | 'Unkown';

export const DomainEnumsProjectVisibility = {
    Draft: 'Draft' as DomainEnumsProjectVisibility,
    Internal: 'Internal' as DomainEnumsProjectVisibility,
    Public: 'Public' as DomainEnumsProjectVisibility,
    Unkown: 'Unkown' as DomainEnumsProjectVisibility
};