/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsProjectConnectionType = 'Related' | 'SubProject' | 'ParentProject' | 'PredecessorProject' | 'SuccessorProject';

export const DomainEnumsProjectConnectionType = {
    Related: 'Related' as DomainEnumsProjectConnectionType,
    SubProject: 'SubProject' as DomainEnumsProjectConnectionType,
    ParentProject: 'ParentProject' as DomainEnumsProjectConnectionType,
    PredecessorProject: 'PredecessorProject' as DomainEnumsProjectConnectionType,
    SuccessorProject: 'SuccessorProject' as DomainEnumsProjectConnectionType
};