/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DomainEnumsProjectType = 0 | 1 | 2 | 3 | 4;

export const DomainEnumsProjectType = {
    NUMBER_0: 0 as DomainEnumsProjectType,
    NUMBER_1: 1 as DomainEnumsProjectType,
    NUMBER_2: 2 as DomainEnumsProjectType,
    NUMBER_3: 3 as DomainEnumsProjectType,
    NUMBER_4: 4 as DomainEnumsProjectType
};