apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perspektivenfabrik-postgres-pvc
  namespace: perspektivenfabrik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi