apiVersion: apps/v1
kind: Deployment
metadata:
  name: perspektivenfabrik-proxy-deployment
  namespace: perspektivenfabrik
spec:
  selector:
    matchLabels:
      app: perspektivenfabrik-proxy-pod
  template:
    metadata:
      labels:
        app: perspektivenfabrik-proxy-pod
    spec:
      containers:
        - name: perspektivenfabrik-proxy-container
          image: ghcr.io/aschuhde/perspektivenfabrik-proxy:main
          ports:
            - containerPort: 9000
            - containerPort: 9443
          envFrom:
            - configMapRef:
                name: perspektivenfabrik-proxy-config
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perspektivenfabrik-nginx-deployment
  namespace: perspektivenfabrik
spec:
  selector:
    matchLabels:
      app: perspektivenfabrik-nginx-pod
  template:
    metadata:
      labels:
        app: perspektivenfabrik-nginx-pod
    spec:
      containers:
        - name: perspektivenfabrik-nginx-container
          image: ghcr.io/aschuhde/perspektivenfabrik-frontend-container:main
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: perspektivenfabrik-proxy-config
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perspektivenfabrik-angular-deployment
  namespace: perspektivenfabrik
spec:
  selector:
    matchLabels:
      app: perspektivenfabrik-angular-pod
  template:
    metadata:
      labels:
        app: perspektivenfabrik-angular-pod
    spec:
      containers:
        - name: perspektivenfabrik-angular-container
          image: ghcr.io/aschuhde/perspektivenfabrik-frontend:main
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: perspektivenfabrik-proxy-config
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perspektivenfabrik-api-deployment
  namespace: perspektivenfabrik
spec:
  selector:
    matchLabels:
      app: perspektivenfabrik-api-pod
  template:
    metadata:
      labels:
        app: perspektivenfabrik-api-pod      
    spec:
      containers:
        - name: perspektivenfabrik-api-container
          image: ghcr.io/aschuhde/perspektivenfabrik-api:main
          ports:
            - containerPort: 8001
          env:
            - name: CONFIG_Serilog__MinimumLevel__Default
              value: Debug            
          envFrom:
            - configMapRef:
                name: perspektivenfabrik-api-config
            - configMapRef:
                name: perspektivenfabrik-db-config
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /api/healthz/ready
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 80
              path: /api/healthz/live
            initialDelaySeconds: 15
            timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perspektivenfabrik-postgres-deployment
  namespace: perspektivenfabrik
spec:
  selector:
    matchLabels:
      app: perspektivenfabrik-postgres-pod
  template:
    metadata:
      labels:
        app: perspektivenfabrik-postgres-pod
    spec:
      containers:
        - name: perspektivenfabrik-postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: perspektivenfabrik-db-config
          volumeMounts:
            - name: perspektivenfabrik-postgres-storage
              mountPath: /var/lib/postgresql/data
          imagePullPolicy: Always
      volumes:
        - name: perspektivenfabrik-postgres-storage
          persistentVolumeClaim:
            claimName: perspektivenfabrik-postgres-pvc
---
# Service for Angular
apiVersion: v1
kind: Service
metadata:
  name: perspektivenfabrik-angular-service
  namespace: perspektivenfabrik
spec:
  selector:
    app: perspektivenfabrik-angular-pod
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
---
# Service for Nginx
apiVersion: v1
kind: Service
metadata:
  name: perspektivenfabrik-nginx-service
  namespace: perspektivenfabrik
spec:
  selector:
    app: perspektivenfabrik-nginx-pod
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
---
# Service for API
apiVersion: v1
kind: Service
metadata:
  name: perspektivenfabrik-api-service
  namespace: perspektivenfabrik
spec:
  selector:
    app: perspektivenfabrik-api-pod
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: perspektivenfabrik-proxy-service
  namespace: perspektivenfabrik
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_main_aks1_germanywestcentral
    service.beta.kubernetes.io/azure-pip-name: perspektivenfabrikPublicIP
    service.beta.kubernetes.io/azure-dns-label-name: perspektivenfabrik-aks1
spec:
  selector:
    app: perspektivenfabrik-proxy-pod
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: https
      port: 9443
      targetPort: 9443
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: perspektivenfabrik-postgres-service
  namespace: perspektivenfabrik
spec:
  selector:
    app: perspektivenfabrik-postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP