using Application.GetJsonTypeDiscriminatorNames.GetJsonTypeDiscriminatorNames;
using WebApi.Attributes;

namespace WebApi.Endpoints;

[HttpGet(Constants.Routes.GetJsonTypeDiscriminatorNames)]
public class GetJsonTypeDiscriminatorNames : JsonResponseEndpoint<GetJsonTypeDiscriminatorNamesRequest, GetJsonTypeDiscriminatorNamesResponse>;