name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./src/Proxy/Dockerfile
            image: ghcr.io/aschuhde/perspektivenfabrik-proxy
            context: ./
          - dockerfile: ./src/Frontend/Dockerfile
            image: ghcr.io/aschuhde/perspektivenfabrik-frontend
            context: ./src/Frontend
          - dockerfile: ./src/NginxFrontendProxy/Dockerfile            
            image: ghcr.io/aschuhde/perspektivenfabrik-frontend-container
            context: ./src/NginxFrontendProxy
          - dockerfile: ./src/WebApi/Dockerfile
            image: ghcr.io/aschuhde/perspektivenfabrik-api
            context: ./
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
