name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted
    environment: production
    env:
      PROXY_CERTIFICATE: ${{ secrets.PROXY_CERTIFICATE }}
      PROXY_CERTIFICATE_PASSWORD: ${{ secrets.PROXY_CERTIFICATE_PASSWORD }}
      GLOBAL_ACCESS_TOKEN: ${{ GLOBAL_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3    
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yaml up -d
